[package]
name = "bazbot"
version = "0.2.5"
authors = ["Joel Roller <roller@gmail.com>"]
license = "CC0-1.0"
readme = "README.md"

[dependencies]
irc = "0.12"
dotenv = "0.13"
rusqlite = "0.14"
clap = "2.33"
rand = "0.6"
log = "0.4"
env_logger = "0.6"
